// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collaborators.sql

package sqlc

import (
	"context"
)

const deleteCollaborator = `-- name: DeleteCollaborator :exec
DELETE FROM roadmap_collaborators WHERE roadmap_id = $1 AND user_id = $2
`

type DeleteCollaboratorParams struct {
	RoadmapID int64 `json:"roadmap_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) DeleteCollaborator(ctx context.Context, arg DeleteCollaboratorParams) error {
	_, err := q.db.Exec(ctx, deleteCollaborator, arg.RoadmapID, arg.UserID)
	return err
}

const getCollaborator = `-- name: GetCollaborator :one
SELECT roadmap_id, user_id, can_edit, can_share
FROM roadmap_collaborators
WHERE roadmap_id = $1 AND user_id = $2
`

type GetCollaboratorParams struct {
	RoadmapID int64 `json:"roadmap_id"`
	UserID    int64 `json:"user_id"`
}

type GetCollaboratorRow struct {
	RoadmapID int64 `json:"roadmap_id"`
	UserID    int64 `json:"user_id"`
	CanEdit   bool  `json:"can_edit"`
	CanShare  bool  `json:"can_share"`
}

func (q *Queries) GetCollaborator(ctx context.Context, arg GetCollaboratorParams) (GetCollaboratorRow, error) {
	row := q.db.QueryRow(ctx, getCollaborator, arg.RoadmapID, arg.UserID)
	var i GetCollaboratorRow
	err := row.Scan(
		&i.RoadmapID,
		&i.UserID,
		&i.CanEdit,
		&i.CanShare,
	)
	return i, err
}

const listCollaboratorsByRoadmap = `-- name: ListCollaboratorsByRoadmap :many
SELECT c.roadmap_id, c.user_id, c.can_edit, c.can_share,
       u.name AS user_name, u.email AS user_email
FROM roadmap_collaborators c
JOIN users u ON u.id = c.user_id
WHERE c.roadmap_id = $1
ORDER BY u.name ASC
`

type ListCollaboratorsByRoadmapRow struct {
	RoadmapID int64  `json:"roadmap_id"`
	UserID    int64  `json:"user_id"`
	CanEdit   bool   `json:"can_edit"`
	CanShare  bool   `json:"can_share"`
	UserName  string `json:"user_name"`
	UserEmail string `json:"user_email"`
}

func (q *Queries) ListCollaboratorsByRoadmap(ctx context.Context, roadmapID int64) ([]ListCollaboratorsByRoadmapRow, error) {
	rows, err := q.db.Query(ctx, listCollaboratorsByRoadmap, roadmapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollaboratorsByRoadmapRow
	for rows.Next() {
		var i ListCollaboratorsByRoadmapRow
		if err := rows.Scan(
			&i.RoadmapID,
			&i.UserID,
			&i.CanEdit,
			&i.CanShare,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyCollaborations = `-- name: ListMyCollaborations :many
SELECT roadmap_id, can_edit, can_share
FROM roadmap_collaborators
WHERE user_id = $1
`

type ListMyCollaborationsRow struct {
	RoadmapID int64 `json:"roadmap_id"`
	CanEdit   bool  `json:"can_edit"`
	CanShare  bool  `json:"can_share"`
}

func (q *Queries) ListMyCollaborations(ctx context.Context, userID int64) ([]ListMyCollaborationsRow, error) {
	rows, err := q.db.Query(ctx, listMyCollaborations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyCollaborationsRow
	for rows.Next() {
		var i ListMyCollaborationsRow
		if err := rows.Scan(&i.RoadmapID, &i.CanEdit, &i.CanShare); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCollaborator = `-- name: UpsertCollaborator :one
INSERT INTO roadmap_collaborators (roadmap_id, user_id, can_edit, can_share, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (roadmap_id, user_id) DO UPDATE
SET can_edit = EXCLUDED.can_edit, can_share = EXCLUDED.can_share
RETURNING roadmap_id, user_id, can_edit, can_share
`

type UpsertCollaboratorParams struct {
	RoadmapID int64  `json:"roadmap_id"`
	UserID    int64  `json:"user_id"`
	CanEdit   bool   `json:"can_edit"`
	CanShare  bool   `json:"can_share"`
	CreatedBy *int64 `json:"created_by"`
}

type UpsertCollaboratorRow struct {
	RoadmapID int64 `json:"roadmap_id"`
	UserID    int64 `json:"user_id"`
	CanEdit   bool  `json:"can_edit"`
	CanShare  bool  `json:"can_share"`
}

// UpsertCollaborator cria ou atualiza o vínculo. Reconvidar atualiza permissões.
func (q *Queries) UpsertCollaborator(ctx context.Context, arg UpsertCollaboratorParams) (UpsertCollaboratorRow, error) {
	row := q.db.QueryRow(ctx, upsertCollaborator,
		arg.RoadmapID,
		arg.UserID,
		arg.CanEdit,
		arg.CanShare,
		arg.CreatedBy,
	)
	var i UpsertCollaboratorRow
	err := row.Scan(
		&i.RoadmapID,
		&i.UserID,
		&i.CanEdit,
		&i.CanShare,
	)
	return i, err
}
