// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countItems = `-- name: CountItems :one
SELECT COUNT(*) FROM roadmap_items
`

func (q *Queries) CountItems(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countItems)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO roadmap_items (
    title, status, start_date, end_date, progress, dependency_id, notes,
    ext_team, ext_description, ext_milestone, sort_order
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, title, status, start_date, end_date, progress, dependency_id,
          notes, ext_team, ext_description, ext_milestone, sort_order,
          created_at, updated_at
`

type CreateItemParams struct {
	Title          string      `json:"title"`
	Status         string      `json:"status"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	Progress       int32       `json:"progress"`
	DependencyID   *int64      `json:"dependency_id"`
	Notes          string      `json:"notes"`
	ExtTeam        *string     `json:"ext_team"`
	ExtDescription *string     `json:"ext_description"`
	ExtMilestone   pgtype.Date `json:"ext_milestone"`
	SortOrder      int32       `json:"sort_order"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (RoadmapItem, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Title,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.Progress,
		arg.DependencyID,
		arg.Notes,
		arg.ExtTeam,
		arg.ExtDescription,
		arg.ExtMilestone,
		arg.SortOrder,
	)
	var i RoadmapItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Progress,
		&i.DependencyID,
		&i.Notes,
		&i.ExtTeam,
		&i.ExtDescription,
		&i.ExtMilestone,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM roadmap_items WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, title, status, start_date, end_date, progress, dependency_id,
       notes, ext_team, ext_description, ext_milestone, sort_order,
       created_at, updated_at
FROM roadmap_items
WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id int64) (RoadmapItem, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i RoadmapItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Progress,
		&i.DependencyID,
		&i.Notes,
		&i.ExtTeam,
		&i.ExtDescription,
		&i.ExtMilestone,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT id, title, status, start_date, end_date, progress, dependency_id,
       notes, ext_team, ext_description, ext_milestone, sort_order,
       created_at, updated_at
FROM roadmap_items
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListItems(ctx context.Context) ([]RoadmapItem, error) {
	rows, err := q.db.Query(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoadmapItem
	for rows.Next() {
		var i RoadmapItem
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.Progress,
			&i.DependencyID,
			&i.Notes,
			&i.ExtTeam,
			&i.ExtDescription,
			&i.ExtMilestone,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE roadmap_items SET
    title = $2,
    status = $3,
    start_date = $4,
    end_date = $5,
    progress = $6,
    dependency_id = $7,
    notes = $8,
    ext_team = $9,
    ext_description = $10,
    ext_milestone = $11,
    sort_order = $12,
    updated_at = now()
WHERE id = $1
RETURNING id, title, status, start_date, end_date, progress, dependency_id,
          notes, ext_team, ext_description, ext_milestone, sort_order,
          created_at, updated_at
`

type UpdateItemParams struct {
	ID             int64       `json:"id"`
	Title          string      `json:"title"`
	Status         string      `json:"status"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	Progress       int32       `json:"progress"`
	DependencyID   *int64      `json:"dependency_id"`
	Notes          string      `json:"notes"`
	ExtTeam        *string     `json:"ext_team"`
	ExtDescription *string     `json:"ext_description"`
	ExtMilestone   pgtype.Date `json:"ext_milestone"`
	SortOrder      int32       `json:"sort_order"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (RoadmapItem, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Title,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.Progress,
		arg.DependencyID,
		arg.Notes,
		arg.ExtTeam,
		arg.ExtDescription,
		arg.ExtMilestone,
		arg.SortOrder,
	)
	var i RoadmapItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Progress,
		&i.DependencyID,
		&i.Notes,
		&i.ExtTeam,
		&i.ExtDescription,
		&i.ExtMilestone,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
