// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Roadmap struct {
	ID          int64              `json:"id"`
	OwnerID     int64              `json:"owner_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RoadmapItem struct {
	ID             int64              `json:"id"`
	Title          string             `json:"title"`
	Status         string             `json:"status"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	Progress       int32              `json:"progress"`
	DependencyID   *int64             `json:"dependency_id"`
	Notes          string             `json:"notes"`
	ExtTeam        *string            `json:"ext_team"`
	ExtDescription *string            `json:"ext_description"`
	ExtMilestone   pgtype.Date        `json:"ext_milestone"`
	SortOrder      int32              `json:"sort_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Color          *string            `json:"color"`
	EpicUrl        *string            `json:"epic_url"`
	RoadmapID      *int64             `json:"roadmap_id"`
}

type Session struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
