// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roadmaps.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoadmap = `-- name: CreateRoadmap :one
INSERT INTO roadmaps (owner_id, name, slug, description)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, slug, description, created_at, updated_at
`

type CreateRoadmapParams struct {
	OwnerID     int64  `json:"owner_id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

func (q *Queries) CreateRoadmap(ctx context.Context, arg CreateRoadmapParams) (Roadmap, error) {
	row := q.db.QueryRow(ctx, createRoadmap,
		arg.OwnerID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Roadmap
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoadmap = `-- name: DeleteRoadmap :exec
DELETE FROM roadmaps WHERE id = $1
`

func (q *Queries) DeleteRoadmap(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRoadmap, id)
	return err
}

const getRoadmapByID = `-- name: GetRoadmapByID :one
SELECT id, owner_id, name, slug, description, created_at, updated_at
FROM roadmaps
WHERE id = $1
`

func (q *Queries) GetRoadmapByID(ctx context.Context, id int64) (Roadmap, error) {
	row := q.db.QueryRow(ctx, getRoadmapByID, id)
	var i Roadmap
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoadmapBySlug = `-- name: GetRoadmapBySlug :one
SELECT id, owner_id, name, slug, description, created_at, updated_at
FROM roadmaps
WHERE slug = $1
`

func (q *Queries) GetRoadmapBySlug(ctx context.Context, slug string) (Roadmap, error) {
	row := q.db.QueryRow(ctx, getRoadmapBySlug, slug)
	var i Roadmap
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMyRoadmaps = `-- name: ListMyRoadmaps :many
SELECT r.id, r.owner_id, r.name, r.slug, r.description, r.created_at, r.updated_at,
       u.name AS owner_name,
       (SELECT COUNT(*) FROM roadmap_items i WHERE i.roadmap_id = r.id) AS item_count
FROM roadmaps r
JOIN users u ON u.id = r.owner_id
WHERE r.owner_id = $1
ORDER BY r.name ASC
`

type ListMyRoadmapsRow struct {
	ID          int64              `json:"id"`
	OwnerID     int64              `json:"owner_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OwnerName   string             `json:"owner_name"`
	ItemCount   int64              `json:"item_count"`
}

func (q *Queries) ListMyRoadmaps(ctx context.Context, ownerID int64) ([]ListMyRoadmapsRow, error) {
	rows, err := q.db.Query(ctx, listMyRoadmaps, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyRoadmapsRow
	for rows.Next() {
		var i ListMyRoadmapsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoadmaps = `-- name: ListRoadmaps :many
SELECT r.id, r.owner_id, r.name, r.slug, r.description, r.created_at, r.updated_at,
       u.name AS owner_name,
       (SELECT COUNT(*) FROM roadmap_items i WHERE i.roadmap_id = r.id) AS item_count
FROM roadmaps r
JOIN users u ON u.id = r.owner_id
ORDER BY r.name ASC
`

type ListRoadmapsRow struct {
	ID          int64              `json:"id"`
	OwnerID     int64              `json:"owner_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	OwnerName   string             `json:"owner_name"`
	ItemCount   int64              `json:"item_count"`
}

func (q *Queries) ListRoadmaps(ctx context.Context) ([]ListRoadmapsRow, error) {
	rows, err := q.db.Query(ctx, listRoadmaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoadmapsRow
	for rows.Next() {
		var i ListRoadmapsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerName,
			&i.ItemCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoadmap = `-- name: UpdateRoadmap :one
UPDATE roadmaps
SET name = $2, slug = $3, description = $4, updated_at = now()
WHERE id = $1
RETURNING id, owner_id, name, slug, description, created_at, updated_at
`

type UpdateRoadmapParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
	Description string `json:"description"`
}

func (q *Queries) UpdateRoadmap(ctx context.Context, arg UpdateRoadmapParams) (Roadmap, error) {
	row := q.db.QueryRow(ctx, updateRoadmap,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Roadmap
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
