// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users WHERE role = 'admin'
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	Token     string             `json:"token"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, role, auth_provider, must_change_password)
VALUES ($1, $2, $3, $4, 'local', true)
RETURNING id, email, name, role, auth_provider, created_at
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
	Name         string  `json:"name"`
	Role         string  `json:"role"`
}

type CreateUserRow struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	AuthProvider string             `json:"auth_provider"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// CreateUser registra uma conta com senha definida pelo admin. Como essa senha
// é temporária (o admin não conhecerá a senha definitiva do usuário), a conta
// nasce marcada para troca obrigatória no primeiro acesso.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.AuthProvider,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const ensureDemoUser = `-- name: EnsureDemoUser :one
INSERT INTO users (email, name, role, auth_provider)
VALUES ($1, $2, 'user', 'local')
ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

type EnsureDemoUserParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// EnsureDemoUser cria um usuário fictício do conjunto de demonstração.
// Nasce SEM senha (password_hash nulo), portanto não é porta de entrada na
// URL pública da VM: existe para ser dono e colaborador de roadmaps. Em
// desenvolvimento ainda se entra como ele pelo dev login.
// CreateUser não serve aqui porque fixa must_change_password = true no SQL.
func (q *Queries) EnsureDemoUser(ctx context.Context, arg EnsureDemoUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, ensureDemoUser, arg.Email, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ensureDevUser = `-- name: EnsureDevUser :one
INSERT INTO users (email, name, role, auth_provider)
VALUES ($1, 'Dev', 'admin', 'local')
ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

// EnsureDevUser cria, sob demanda, a conta usada pelo login de desenvolvimento
// (POST /api/dev/login, registrado apenas com DEV_MODE). Nasce sem senha e SEM
// troca obrigatória: o endpoint existe justamente para dispensar o fluxo de
// autenticação em testes automatizados, e exigir troca de senha aqui levaria
// toda captura de tela para a tela de troca de senha.
func (q *Queries) EnsureDevUser(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, ensureDevUser, email)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ensureSeedUser = `-- name: EnsureSeedUser :one
INSERT INTO users (email, password_hash, name, role, must_change_password)
VALUES ($1, $2, $3, $4, true)
ON CONFLICT (email) DO UPDATE
SET name = EXCLUDED.name,
    role = EXCLUDED.role
RETURNING id
`

type EnsureSeedUserParams struct {
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
	Name         string  `json:"name"`
	Role         string  `json:"role"`
}

// EnsureSeedUser garante a existência da conta de administrador inicial.
// Não é um upsert completo de propósito: `password_hash` e
// `must_change_password` são definidos APENAS na criação. Sobrescrevê-los em
// todo boot desfaria a troca de senha feita pelo usuário e o devolveria à tela
// de troca obrigatória depois de cada deploy.
func (q *Queries) EnsureSeedUser(ctx context.Context, arg EnsureSeedUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, ensureSeedUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSession = `-- name: GetSession :one
SELECT s.token, s.user_id, s.expires_at, u.email, u.name, u.role, u.must_change_password
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = $1 AND s.expires_at > now()
`

type GetSessionRow struct {
	Token              string             `json:"token"`
	UserID             int64              `json:"user_id"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	Email              string             `json:"email"`
	Name               string             `json:"name"`
	Role               string             `json:"role"`
	MustChangePassword bool               `json:"must_change_password"`
}

func (q *Queries) GetSession(ctx context.Context, token string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, token)
	var i GetSessionRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.MustChangePassword,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, must_change_password, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                 int64              `json:"id"`
	Email              string             `json:"email"`
	PasswordHash       *string            `json:"password_hash"`
	Name               string             `json:"name"`
	Role               string             `json:"role"`
	MustChangePassword bool               `json:"must_change_password"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.MustChangePassword,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, created_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, role, auth_provider, created_at
FROM users
ORDER BY name ASC
`

type ListUsersRow struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	AuthProvider string             `json:"auth_provider"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.AuthProvider,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetUserPassword = `-- name: ResetUserPassword :exec
UPDATE users SET password_hash = $2, must_change_password = true WHERE id = $1
`

type ResetUserPasswordParams struct {
	ID           int64   `json:"id"`
	PasswordHash *string `json:"password_hash"`
}

// ResetUserPassword (admin) define uma senha temporária para outro usuário e
// marca a conta para troca obrigatória no próximo acesso. Não exige a senha
// antiga — é a alternativa ao fluxo de "esqueci minha senha".
func (q *Queries) ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, resetUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const searchUsersForRoadmap = `-- name: SearchUsersForRoadmap :many
SELECT u.id, u.email, u.name
FROM users u
WHERE (u.email ILIKE '%' || $1 || '%' OR u.name ILIKE '%' || $1 || '%')
  AND u.id <> (SELECT r.owner_id FROM roadmaps r WHERE r.id = $2)
  AND NOT EXISTS (
    SELECT 1 FROM roadmap_collaborators rc
    WHERE rc.roadmap_id = $2 AND rc.user_id = u.id
  )
ORDER BY u.name ASC
LIMIT 10
`

type SearchUsersForRoadmapParams struct {
	Query     *string `json:"query"`
	RoadmapID int64   `json:"roadmap_id"`
}

type SearchUsersForRoadmapRow struct {
	ID    int64  `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}

// SearchUsersForRoadmap alimenta o autocomplete do compartilhamento: busca por
// e-mail OU nome, excluindo o dono e quem já é colaborador do roadmap.
// O parâmetro @query já chega com os curingas LIKE escapados pelo handler.
func (q *Queries) SearchUsersForRoadmap(ctx context.Context, arg SearchUsersForRoadmapParams) ([]SearchUsersForRoadmapRow, error) {
	rows, err := q.db.Query(ctx, searchUsersForRoadmap, arg.Query, arg.RoadmapID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersForRoadmapRow
	for rows.Next() {
		var i SearchUsersForRoadmapRow
		if err := rows.Scan(&i.ID, &i.Email, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOwnName = `-- name: UpdateOwnName :one
UPDATE users SET name = $2 WHERE id = $1
RETURNING id, email, name, role, auth_provider, created_at
`

type UpdateOwnNameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type UpdateOwnNameRow struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	AuthProvider string             `json:"auth_provider"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// UpdateOwnName altera o nome da própria conta do usuário logado.
func (q *Queries) UpdateOwnName(ctx context.Context, arg UpdateOwnNameParams) (UpdateOwnNameRow, error) {
	row := q.db.QueryRow(ctx, updateOwnName, arg.ID, arg.Name)
	var i UpdateOwnNameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.AuthProvider,
		&i.CreatedAt,
	)
	return i, err
}

const updateOwnPassword = `-- name: UpdateOwnPassword :exec
UPDATE users SET password_hash = $2, must_change_password = false WHERE id = $1
`

type UpdateOwnPasswordParams struct {
	ID           int64   `json:"id"`
	PasswordHash *string `json:"password_hash"`
}

// UpdateOwnPassword define um novo hash de senha para a própria conta e
// desliga a obrigatoriedade de troca: ao escolher a senha, o usuário cumpriu a
// exigência do primeiro acesso.
func (q *Queries) UpdateOwnPassword(ctx context.Context, arg UpdateOwnPasswordParams) error {
	_, err := q.db.Exec(ctx, updateOwnPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2 WHERE id = $1
RETURNING id, email, name, role, auth_provider, created_at
`

type UpdateUserRoleParams struct {
	ID   int64  `json:"id"`
	Role string `json:"role"`
}

type UpdateUserRoleRow struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         string             `json:"role"`
	AuthProvider string             `json:"auth_provider"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i UpdateUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.AuthProvider,
		&i.CreatedAt,
	)
	return i, err
}
